export const activities = [
    { label: 'Running', value: 'Running' },
    { label: 'Cycling', value: 'Cycling' },
    { label: 'Swimming', value: 'Swimming' },
    { label: 'Hiking', value: 'Hiking' },
    { label: 'Walking', value: 'Walking' },
    { label: 'Jogging', value: 'Jogging' },
    { label: 'Yoga', value: 'Yoga' },
    { label: 'Pilates', value: 'Pilates' },
    { label: 'Weightlifting', value: 'Weightlifting' },
    { label: 'CrossFit', value: 'CrossFit' },
    { label: 'Rowing', value: 'Rowing' },
    { label: 'Rock climbing', value: 'Rock climbing' },
    { label: 'Skateboarding', value: 'Skateboarding' },
    { label: 'Surfing', value: 'Surfing' },
    { label: 'Rollerblading', value: 'Rollerblading' },
    { label: 'Jump rope', value: 'Jump rope' },
    { label: 'Martial arts', value: 'Martial arts' },
    { label: 'Tennis', value: 'Tennis' },
    { label: 'Soccer', value: 'Soccer' },
    { label: 'Basketball', value: 'Basketball' },
    { label: 'Volleyball', value: 'Volleyball' },
    { label: 'Badminton', value: 'Badminton' },
    { label: 'Golf', value: 'Golf' },
    { label: 'Frisbee', value: 'Frisbee' },
    { label: 'Ultimate Frisbee', value: 'Ultimate Frisbee' },
    { label: 'Cricket', value: 'Cricket' },
    { label: 'Rugby', value: 'Rugby' },
    { label: 'Football', value: 'Football' },
    { label: 'Baseball', value: 'Baseball' },
    { label: 'Softball', value: 'Softball' },
    { label: 'Handball', value: 'Handball' },
    { label: 'Squash', value: 'Squash' },
    { label: 'Table tennis', value: 'Table tennis' },
    { label: 'Archery', value: 'Archery' },
    { label: 'Horseback riding', value: 'Horseback riding' },
    { label: 'Kayaking', value: 'Kayaking' },
    { label: 'Canoeing', value: 'Canoeing' },
    { label: 'Rafting', value: 'Rafting' },
    { label: 'Fishing', value: 'Fishing' },
    { label: 'Hunting', value: 'Hunting' },
    { label: 'Orienteering', value: 'Orienteering' },
    { label: 'Geocaching', value: 'Geocaching' },
    { label: 'Birdwatching', value: 'Birdwatching' },
    { label: 'Nature photography', value: 'Nature photography' },
    { label: 'Stargazing', value: 'Stargazing' },
    { label: 'Camping', value: 'Camping' },
    { label: 'Backpacking', value: 'Backpacking' },
    { label: 'Picnicking', value: 'Picnicking' },
    { label: 'Scuba diving', value: 'Scuba diving' },
    { label: 'Snorkeling', value: 'Snorkeling' },
    { label: 'Sailing', value: 'Sailing' },
    { label: 'Windsurfing', value: 'Windsurfing' },
    { label: 'Kiteboarding', value: 'Kiteboarding' },
    { label: 'Paragliding', value: 'Paragliding' },
    { label: 'Hang gliding', value: 'Hang gliding' },
    { label: 'Bungee jumping', value: 'Bungee jumping' },
    { label: 'Skydiving', value: 'Skydiving' },
    { label: 'Zip-lining', value: 'Zip-lining' },
    { label: 'Rock scrambling', value: 'Rock scrambling' },
    { label: 'Caving', value: 'Caving' },
    { label: 'Mountaineering', value: 'Mountaineering' },
    { label: 'Ice climbing', value: 'Ice climbing' },
    { label: 'Snowboarding', value: 'Snowboarding' },
    { label: 'Skiing', value: 'Skiing' },
    { label: 'Snowshoeing', value: 'Snowshoeing' },
    { label: 'Ice skating', value: 'Ice skating' },
    { label: 'Sledding', value: 'Sledding' },
    { label: 'Snow tubing', value: 'Snow tubing' },
    { label: 'Snowmobiling', value: 'Snowmobiling' },
    { label: 'Dog sledding', value: 'Dog sledding' },
    { label: 'Biathlon', value: 'Biathlon' },
    { label: 'Cross-country skiing', value: 'Cross-country skiing' },
    { label: 'Nordic walking', value: 'Nordic walking' },
    { label: 'Trail running', value: 'Trail running' },
    { label: 'Parkour', value: 'Parkour' },
    { label: 'Slacklining', value: 'Slacklining' },
    { label: 'Trampoline', value: 'Trampoline' },
    { label: 'Park workouts', value: 'Park workouts' },
    { label: 'Bodyweight exercises', value: 'Bodyweight exercises' },
    { label: 'HIIT (High-Intensity Interval Training)', value: 'HIIT (High-Intensity Interval Training)' },
    { label: 'Circuit training', value: 'Circuit training' },
    { label: 'Plyometrics', value: 'Plyometrics' },
    { label: 'Functional training', value: 'Functional training' },
    { label: 'Calisthenics', value: 'Calisthenics' },
    { label: 'Stretching', value: 'Stretching' },
    { label: 'Balance exercises', value: 'Balance exercises' },
    { label: 'Agility drills', value: 'Agility drills' },
    { label: 'Core workouts', value: 'Core workouts' },
    { label: 'Flexibility training', value: 'Flexibility training' },
    { label: 'Resistance band exercises', value: 'Resistance band exercises' },
    { label: 'Medicine ball workouts', value: 'Medicine ball workouts' },
    { label: 'Kettlebell exercises', value: 'Kettlebell exercises' },
  ]
  
  export default {
      activities,
  }